print("Please enter the number of lives.")
lives = int(input())
print("Please enter the energy level.")
energy_level = int(input())
print("Please enter the shield level.")
shield_level = int(input())
print("Health has been set")
print()
print("lives:{}".format(lives*"\u2764"))
print()
print("energy:{}".format(energy_level*"\u26a1"))
print()
print("shield:{}".format(shield_level*"\u1f616"))